apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: karim3333/app-gsx:v1
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: backend-storage
              mountPath: /data
      volumes:
        - name: backend-storage
          persistentVolumeClaim:
            claimName: backend-pvc